export const TRADING_PAIRS = ["USDC-XLM", "VELO-XLM", "RIO-XLM"] as const;

export const TOKENS = ["XLM", "USDC", "VELO", "RIO"];

export const BASE_CURRENCY_RATIOS = {
  "USDC-XLM": 10.5,
  "VELO-XLM": 0.9,
  "RIO-XLM": 8.88,
};

export const TOKEN_ADDRESSES = {
  XLM: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC", //native testnet
  USDC: "CCGGTGRR7BB3CJHAF3UE7XCNHMZU3ETEFEXYJKSNCCWMQOTA4NTEOKDX", //IDEA1
  VELO: "CCHLAZS3356JL6R7BPDKCA2EZV2KMYDBXPWHUI5MXFI5KUHRN2SMP2HY", //IDEA2
  RIO: "CAODHI5KBUZWPG2WT5EOLX27BQ6LO6SLS7INHWFXCHTI4IRJVHSWQ3ZF", //IDEA3
} as const;

export const SOROBAN_URL = "https://soroban-testnet.stellar.org:443";
