export const TRADING_PAIRS = ["USDC-XLM", "VELO-XLM", "RIO-XLM"] as const;

export const TOKENS = ["XLM", "USDC", "VELO", "RIO"];

export const BASE_CURRENCY_RATIOS = {
  "USDC-XLM": 10.5,
  "VELO-XLM": 0.9,
  "RIO-XLM": 8.88,
};

export const TOKEN_ADDRESSES = {
  XLM: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC", //native testnet
  USDC: "CBTOSWUM5OO6JFFGT3PVLWBKPI5TT6ZTN7EXU7ZTEJUAVUJENTMOIOHJ", //IDEA1
  VELO: "CDZIXMJR5EE2PNSAXW2L4STQPEFUT5FWQHAJYVXSYHWQLBOHCD6HRM22", //IDEA2
  RIO: "CA5TCEFSREORJ4UGM3N3YZ2LP23BJG54PIGOLYJSH33WNMYXFVZCFA2D", //IDEA3
} as const;

export const SOROBAN_URL = "https://soroban-testnet.stellar.org:443";
