export const en = {
  'page.header.connect': 'Connect Wallet',
  'page.header.links.trading': 'Trade',
  'page.header.links.reports': 'Reports',
  'page.header.trade.derivarives': 'Derivatives',
  'page.header.trade.spot': 'Spot',

  'page.swap.orderbook.title': 'Order Book',
  'page.swap.orderbook.price': 'Price',
  'page.swap.orderbook.size': 'Size',
  'page.swap.orderbook.sum': 'Sum',

  'page.swap.subheader.favorite': 'Favorite',

  'page.swap.trades.title': 'Trades',
  'page.swap.trades.price': 'Price',
  'page.swap.trades.amount': 'Amount',
  'page.swap.trades.time': 'Time',

  'page.swap.marketsHeader.index': 'Index',
  'page.swap.marketsHeader.premium': 'Premium',
  'page.swap.marketsHeader.funding.countdown': 'Funding / Countdown',
  'page.swap.marketsHeader.change24h': '24h Change',
  'page.swap.marketsHeader.high24h': '24h high',
  'page.swap.marketsHeader.low24h': '24h low',
  'page.swap.marketsHeader.volume24h': '24h Volume',

  'page.swap.assets.title': 'Assets',
  'page.swap.assets.buy': 'Buy',
  'page.swap.assets.trade.balance': 'Trading Balance',
  'page.swap.assets.unrealized': 'Unrealized',
  'page.swap.assets.token': 'Token',
  'page.swap.assets.button.deposit': 'Deposit',
  'page.swap.assets.button.withdraw': 'Withdraw',

  'page.swap.margin.title': 'Margin Data',
  'page.swap.margin.leverage': 'Porfolio Leverage',
  'page.swap.margin.minmargin': 'Min Margin',
  'page.swap.margin.equity': 'Equity',

  'page.swap.orderform.title': 'Spot',
  'page.swap.orderform.limit': 'Limit',
  'page.swap.orderform.market': 'Market',
  'page.swap.orderform.stop.limit': 'Stop Limit',
  'page.swap.orderform.price': 'Price',
  'page.swap.orderform.leverage': 'Leverage',
  'page.swap.orderform.stop': 'Stop',
  'page.swap.orderform.size': 'Size ',
  'page.swap.orderform.amount': 'Amount',
  'page.swap.orderform.fee': 'Type of fee',
  'page.swap.orderform.buy': 'Buy/Long',
  'page.swap.orderform.sell': 'Sell/Short',
  'page.swap.orderform.max': 'Max',

  'page.swap.derivativeform.title': 'Derivatives',
  'page.swap.derivativeform.cross': 'Cross',
  'page.swap.derivativeform.limit': 'Limit',
  'page.swap.derivativeform.market': 'Market',
  'page.swap.derivativeform.stop.price': 'Stop Limit',
  'page.swap.derivativeform.stop': 'Stop',
  'page.swap.derivativeform.price': 'Price',
  'page.swap.derivativeform.size': 'Size',
  'page.swap.derivativeform.buy': 'Buy/Long',
  'page.swap.derivativeform.sell': 'Sell/Short',
  'page.swap.derivativeform.max': 'Max',
  'page.swap.derivetiveform.or': 'or',
  'page.swap.derivativeform.leverage': 'Leverage',

  'page.swap.positions.title': 'Positions',
  'page.swap.position.table.pair': 'Pair',
  'page.swap.position.table.amount': 'Amount',
  'page.swap.position.table.base.price': 'Base Price',
  'page.swap.position.table.liq.price': 'Liq Price',
  'page.swap.position.table.pl': 'P/L',
  'page.swap.position.table.pl.percentage': 'P/L%',
  'page.swap.position.table.actions.market': 'Market',
  'page.swap.position.table.actions.limit': 'Limit',

  'page.swap.open.orders.title': 'Open Orders',
  'page.swap.open.orders.table.pair': 'Pair',
  'page.swap.open.orders.table.type': 'Type',
  'page.swap.open.orders.table.amount': 'Amount',
  'page.swap.open.orders.table.price': 'Price',
  'page.swap.open.orders.table.placed': 'Placed',

  'page.swap.history.title': 'History',
  'page.swap.history.table.pair': 'Pair',
  'page.swap.history.table.type': 'Type',
  'page.swap.history.table.amount': 'Amount',
  'page.swap.history.table.price': 'Price',
  'page.swap.history.table.avarage.price': 'Average Execution Price',
  'page.swap.history.table.status': 'Status',
  'page.swap.history.table.inactive': 'Inactive',

  'page.swap.market.selector.all': 'All',
  'page.swap.market.selector.favorites': 'Favorites',
  'page.swap.market.selector.pair': 'Pair',
  'page.swap.market.selector.last.price': 'Last Price',
  'page.swap.market.selector.volume': 'Volume',
  'page.swap.market.selector.change24h': '24h %',

  'page.reports.sidebar.open.orders': 'Open Orders',
  'page.reports.sidebar.order.history': 'Order History',
  'page.reports.sidebar.trade.history': 'Trade History',
  'page.reports.sidebar.transaction.history': 'Transaction History',

  'page.reports.open.orders.title': 'Open Orders',
  'page.reports.open.orders.filter': 'Filter',
  'page.reports.open.orders.symbol': 'Symbol',
  'page.reports.open.orders.side': 'Side',
  'page.reports.open.orders.side.sell': 'Sell',
  'page.reports.open.orders.side.buy': 'Buy',
  'page.reports.open.orders.reset': 'Reset',
  'page.reports.open.orders.all': 'All',
  'page.reports.open.orders.cancel.all': 'Cancel All Orders',

  'page.reports.open.orders.table.pair': 'Pair',
  'page.reports.open.orders.table.type': 'Type',
  'page.reports.open.orders.table.amount': 'Amount',
  'page.reports.open.orders.table.price': 'Price',
  'page.reports.open.orders.table.side': 'Side',
  'page.reports.open.orders.table.filled': 'Filled',
  'page.reports.open.orders.table.notional.value': 'Notional Value',
  'page.reports.open.orders.table.placed': 'Placed',

  'page.dialog.deposit.title': 'Deposit',
  'page.dialog.deposit.balance': 'Balance',
  'page.dialog.deposit.amount': 'Amount',
  'page.dialog.deposit.approve.message': 'To deposit, you need to approve this token first.',
  'page.dialog.deposit.amount.confirmed': 'Amount confirmed.',
  'page.dialog.deposit.amount.enter': 'Please, set amount to deposit.',
  'page.dialog.deposit.button': 'Deposit ',
  'page.dialog.deposit.approve': 'Approve',
  'page.dialog.deposit.buy': 'Buy',
}
